accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import signup_view, login_view

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup_view, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import ProjectCreateView, ProjectListView, ProjectDetailView

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import TaskCreateView, TaskListView, TaskUpdateView


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=None)
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
CHOICES_YES_NO = ((True, ("yes")), (False, ("no")))


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(
        choices=CHOICES_YES_NO,
        default=False,
    )
    project = models.ForeignKey(
        Project,
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        models.SET_NULL,
        related_name="tasks",
        null=True,
    )

    def __str__(self):
        return self.name


# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password1 = request.POST.get("password")
            user = authenticate(username=username, password=password1)
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("list_projects")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "registration/login.html", context)


# Create your views here.

projects/views.py
from django.views.generic import ListView, DetailView, CreateView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for project in context["object_list"]:
            task = project.tasks
            if task.count() == 0:
                project.percentage_done = 0
            else:
                project.percentage_done = (
                    task.filter(is_completed=True).count() * 100 / task.count()
                )
        return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ["name", "description", "members"]
    template_name = "projects/create.html"

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.id])


# Create your views here.

tasks/views.py
from django.views.generic import CreateView, ListView, UpdateView
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django import template

register = template.Library()


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["percentage_done"] = (
            Task.objects.filter(
                is_completed=True, assignee=self.request.user
            ).count()
            * 100
            / Task.objects.filter(assignee=self.request.user).count()
        )
        return context


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]

    def get_success_url(self) -> str:
        return reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Workspace: Let's get work done!</title>
        <link rel = "stylesheet" href="{% static "css/app.css" %}"> 
    </head>
    <body>
        <header>
            <div class="logo">
            <h1 class="workspace">Workspace</h1>
            </div>
            <div class="link">
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url "show_my_tasks" %}">My tasks</a></li>
                        <li><a href="{% url "list_projects" %}">My projects</a></li>
                        <li><a href="{% url "logout" %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url "login" %}">Login</a></li>
                        <li><a href="{% url "signup" %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
            </div>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
    {% block js %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.12.1/af-2.4.0/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/cr-1.5.6/fc-4.1.0/kt-2.7.0/r-2.3.0/rg-1.2.0/rr-1.2.8/sl-1.4.0/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.12.1/af-2.4.0/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/cr-1.5.6/fc-4.1.0/kt-2.7.0/r-2.3.0/rg-1.2.0/rr-1.2.8/sl-1.4.0/datatables.min.js"></script>
    {% endblock js%}
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="create">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Create">
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}

    <main>
        <h1>{{project.name}}</h1>
        {{project.description|markdownify}}
        <div class="task">
            <h2>Tasks - </h2>
            <h3><i>Check out tasks to be completed!</i></h3>
        </div>
        <p></p>
        <div class="link"><a href="{% url "create_task" %}">Create a new task</a></div>
        {% if project.tasks.all|length == 0%}
            <p>This project has no tasks</p>
        {% else %}
            <table class="content-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </tr>
                    <tbody>
                        {%for task in project.tasks.all %}
                            <tr>
                                <td>{{task.name}}</td>
                                <td>{{task.assignee|title}}</td>
                                <td>{{task.start_date|date:'Y-m-d'}}</td>
                                <td>{{task.due_date|date:'Y-m-d'}}</td>
                                <td>
                                    {% if task.is_completed == True %}
                                        Yes
                                    {% else %}
                                        No
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </thead>
            </table>
        {% endif %}
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <main>
        <div class="greeting">
            <h2>Hello,   
                {{request.user|title}}!      
            </h2>
            <h3><i>Let's get the project done.</i></h3>
            <p>Click each project to see assigned tasks!</p>
        </div>
        <p></p>
        <div>
            <div class="link"><a href="{% url "create_project" %}">Create a new project</a></div>
            <p>
            {% if project_list|length == 0 %}
                <p>You are not assigned to any projects</p>
            {% else %}
                <table class="content-table" id="table_id">
                    <thead>
                        <tr class="active-row">
                            <th>Project</th>
                            <th>Person</th>
                            <th>Number of tasks</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td><b><a href="{% url "show_project" project.pk %}">{{project.name}}</a></b></td>
                                <td>
                                    {% for members in project.members.all %}
                                        {% if forloop.last %} 
                                            {{members|title}}
                                        {% else %}
                                            {{members|title}},
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{project.tasks.all|length}}</td>
                                <td>
                                    {% if project.tasks.all|length == 0 %}
                                        No Task yet!
                                    {% else %}
                                        {{project.percentage_done|floatformat}}% 
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
    $(document).ready( function () {
    $('#table_id').DataTable({

    dom: 'B<"clear">lfrtip',
    buttons: {
        name: 'primary',
        buttons: [ 'copy', 'csv', 'excel', 'pdf' ]

    }}
);
} );
</script>
</div>
{% endblock %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="create">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                <p>
                    <label for="id_name">Name:</label>
                    <input type="text" name="name" maxlength="200" required id="id_name">  
                </p>  
                <p>
                    <label for="id_start_date">Start date:</label>
                    <input type="date" name="start_date" class="vDateField" size="10" required id="id_start_date">
                </p>
                <p>
                    <label for="id_due_date">Due date:</label>
                    <input type="date" name="due_date" class="vDateField" size="10" required id="id_due_date">
                </p>
                <p>
                    <label for="id_project">Project:</label>
                    {{form.project}}                   
                </p>
                <p>
                    <label for="id_assignee">Assignee:</label>                  
                    {{form.assignee}}
                </p> 
                <input type="submit" value="Create">
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if task_list|length == 0 %}
                <p>You have no tasks</p>
            {% else %}
                <table class="content-table" id="table_id">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Project</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td>{{task.name}}</td>
                                <td>{{task.project}}</td>
                                <td>{{task.start_date|date:'Y-m-d'}}</td>
                                <td>{{task.due_date|date:'Y-m-d'}}</td>
                                <td>
                                    {% if task.is_completed == True %}
                                        Done
                                    {% else %}
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button class="button_yellow">Complete</button>
                                        </form>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}


        </main>

{% endblock content %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
    $(document).ready( function () {
    $('#table_id').DataTable({

    dom: 'B<"clear">lfrtip',
    buttons: {
        name: 'primary',
        buttons : [ 'copy', 'csv', 'excel', 'pdf' ]

    }}
);
} );
</script>
</div>
{% endblock %}